version: "3.8"

services:
  app:
    image: node:18.17.1-alpine
    container_name: climatempofront-image
    working_dir: /usr/app
    user: node
    restart: always
    volumes:
      - ./:/usr/app
      - ./src:/usr/app/src
    ports:
      - "8000:4200"
    command: sh -c "npm install && npm run start"

      
        